### ISSUE TITLE
TypeError: rawurlencode(): Argument #1 ($string) must be of type string, int given in laminas-router\src\Http\Regex.php:158

### ISSUE THREAD

**Issue by matbech** [laminas/laminas-router#14]
With the latest update I get the following type error now using PHP 8.0
TypeError: rawurlencode(): Argument #1 ($string) must be of type string, int given in laminas-router\src\Http\Regex.php:158

Stack trace:
```
0 laminas\laminas-router\src\Http\Regex.php(158): rawurlencode(53)
#1 laminas\laminas-router\src\Http\TreeRouteStack.php(373): Laminas\Router\Http\Regex->assemble(Array, Array)
#2 laminas\laminas-router\src\Http\Part.php(219): Laminas\Router\Http\TreeRouteStack->assemble(Array, Array)
#3 laminas\laminas-router\src\Http\TreeRouteStack.php(394): Laminas\Router\Http\Part->assemble(Array, Array)
#4 laminas\laminas-view\src\Helper\Url.php(105): Laminas\Router\Http\TreeRouteStack->assemble(Array, Array)
#5 [internal function]: Laminas\View\Helper\Url->__invoke('localeroute/kb....', Array)
#6 laminas\laminas-view\src\Renderer\PhpRenderer.php(396): call_user_func_array(Object(Laminas\View\Helper\Url), Array)
```

It looks like the problem is when the values passed to the view url helper $options aren't string types:
$options = ['id' => 3 ];
$this->view->url($route, $options);

Is this the correct/expected behavior, then this bug report can be closed.

**Comment by weierophinney** [comment]
Fixed with #15.
